language: node_js
node_js:
    - node

branches:
    only:
        - dev
        - master

cache: yarn

before_install:
    - npm install -g codecov

script:
    - yarn run test --ci && codecov
    - yarn build

jobs:
    include:
        - stage: dev
          node_js: lts/*
          deploy:
              provider: script
              skip_cleanup: true
              before_script: yarn build
              script: npx semantic-release
          on:
              branch: dev
        - stage: production
          node_js: lts/*
          deploy:
              provider: script
              skip_cleanup: true
              before_script: yarn build
              script: npx semantic-release
          on:
              branch: master
